# Generated by Django 6.0.5 on 2026-06-02 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('capacidade', models.IntegerField()),
                ('modelo', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('ONIBUS', 'Ônibus'), ('VAN', 'Van'), ('MICROONIBUS', 'Microônibus')], default='ONIBUS', max_length=20)),
            ],
        ),
    ]
