from .veiculo import VeiculoViewSet
from .planejamento import PlanejamentoViewSet
from .usuario import UsuarioViewSet
from .instituicao import InstituicaoViewSet
from .perfil_passageiro import PerfilPassageiroViewSet
from .perfil_motorista import PerfilMotoristaViewSet
from .confirmacao import ConfirmacaoViewSet
from .advertencia import AdvertenciaViewSet
from .alocacao_veiculo import AlocacaoVeiculoViewSet
from .alocacao_instituicao import AlocacaoInstituicaoViewSet
from .notificacao import NotificacaoViewSet
